# LUMIX fisheye model for 1K setting

Camera:
  name: "fairphone5"
  setup: "monocular"
  model: "perspective"

  fps: 10.0
  cols: 960
  rows: 540

  color_order: "RGB"

Preprocessing:
  min_size: 800

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

Initializer:
  scaling_factor: 5.0

Mapping:
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.9
  num_covisibilities_for_landmark_generation: 20
  num_covisibilities_for_landmark_fusion: 20

System:
  map_format: "msgpack"
  num_grid_cols: 48
  num_grid_rows: 27
